[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow = "Fs7CoR9aA6U49HfdBBZD9eMGCxT782tEjuqiT5Socqww"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
